# Generated by Django 5.2.1 on 2026-05-26 13:53

import attendance.models
import attendance.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('selfie', models.ImageField(upload_to=attendance.models.attendance_selfie_upload_path, validators=[attendance.validators.validate_selfie_file])),
                ('attendance_type', models.CharField(choices=[('office', 'Office'), ('site', 'Site')], default='office', max_length=10)),
                ('status', models.CharField(choices=[('punched_in', 'Punched In'), ('punched_out', 'Punched Out')], default='punched_in', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-punch_in'],
                'indexes': [models.Index(fields=['employee', '-punch_in'], name='attendance__employe_671a35_idx'), models.Index(fields=['attendance_type', '-punch_in'], name='attendance__attenda_b3d56d_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('punch_out__isnull', True)), fields=('employee',), name='unique_open_attendance_per_employee'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='attendance_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='attendance_longitude_range')],
            },
        ),
    ]
