# Generated by Django 5.2.1 on 2026-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('completed', 'Completed'), ('pending', 'Pending')], default='present', max_length=20),
        ),
    ]
