# Generated by Django 5.2.1 on 2026-07-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_sitevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_meetings', to='attendance.attendance'),
        ),
    ]
