# Generated by Django 5.2.1 on 2026-07-15 11:51

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_sitevisit_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=attendance.models.attendance_selfie_upload_path),
        ),
    ]
