# Generated by Django 5.2.1 on 2026-07-16 06:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
